max_steps = 500
seq_len = 32768

[deployment]
num_train_gpus = 1
num_infer_gpus = 1

[model]
name = "Qwen/Qwen3-8B"

[wandb]
project = "half-subdivision-prime-rl"
name = "qwen3-8b-half-subdivision-h100x2"

[orchestrator.wandb.log_extras]
interval = 3

[ckpt]
interval = 25

[trainer.model]
impl = "hf"

[trainer.tokenizer]
name = "Qwen/Qwen3-8B"

[trainer.model.ac]
freq = 1

[trainer.model.lora]
rank = 16
alpha = 32

[trainer.optim]
lr = 1e-5

[orchestrator]
batch_size = 128
rollouts_per_example = 8

[orchestrator.sampling]
max_tokens = 16384

[[orchestrator.env]]
id = "half-subdivision-shaped"
name = "half-subdivision-train-h100x2"
args = { task_name = "half_subdivision" }

[orchestrator.eval]
interval = 10

[orchestrator.eval.sampling]
max_tokens = 16384

[[orchestrator.eval.env]]
id = "half-subdivision-shaped"
name = "half-subdivision-test-h100x2"
args = { task_name = "half_subdivision_test" }
num_examples = 10
rollouts_per_example = 1

[trainer]

[inference.model]
max_model_len = 32768
